In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification
# Create dataset in a way that we dont have to do standardisation

In [4]:
# Create datadset
x,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [5]:
pd.DataFrame(x) # independent features

0         1         2  ...         7         8         9
0    0.964799 -0.066449  0.986768  ... -1.210161 -0.628077  1.227274
1   -0.916511 -0.566395 -1.008614  ... -0.984534  0.363896  0.209470
2   -0.109484 -0.432774 -0.457649  ... -0.246383 -1.058145 -0.297376
3    1.750412  2.023606  1.688159  ... -0.357445 -1.473127 -0.190039
4   -0.224726 -0.711303 -0.220778  ... -0.939156  0.175915  0.236224
..        ...       ...       ...  ...       ...       ...       ...
995 -1.367638  1.462255 -1.154918  ...  1.428760  1.687092  1.072542
996 -1.514876 -3.221016 -1.300744  ... -1.680870  1.798510  0.034272
997  1.674633  1.754933  1.586154  ...  0.692723 -1.503850  0.225264
998 -0.778609 -0.835689 -0.194842  ... -0.497354  2.472138  0.867187
999  0.248454 -1.003439  0.360460  ...  0.773240  0.185734  1.416412

[1000 rows x 10 columns]

In [6]:
pd.DataFrame(y) # dependent features

0
0    0
1    1
2    1
3    0
4    1
..  ..
995  1
996  1
997  0
998  0
999  0

[1000 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=42)

In [8]:
# Model Training
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [9]:
logistic.fit(x_train,y_train)

LogisticRegression()

In [10]:
y_pred = logistic.predict(x_test)
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1
 1 1 1 0]


In [11]:
logistic.predict_log_proba(x_test)

array([[-2.55566142e-01, -1.48933716e+00],
       [-3.39119272e+00, -3.42483315e-02],
       [-3.99459944e-01, -1.11073190e+00],
       [-2.52739499e+00, -8.32368403e-02],
       [-2.36610786e-02, -3.75573105e+00],
       [-3.18550681e+00, -4.22368287e-02],
       [-2.11942527e-02, -3.86460364e+00],
       [-4.14813153e-02, -3.20318115e+00],
       [-2.12549803e-01, -1.65297217e+00],
       [-3.78403132e-01, -1.15503763e+00],
       [-9.02864276e-02, -2.44957172e+00],
       [-1.33333379e+00, -3.05977780e-01],
       [-6.42750323e-01, -7.46219302e-01],
       [-1.55158251e+00, -2.38145969e-01],
       [-2.31185733e-01, -1.57790076e+00],
       [-5.48557608e-02, -2.93035057e+00],
       [-3.63834630e+00, -2.66477107e-02],
       [-1.12635575e+00, -3.91876775e-01],
       [-1.15580638e+00, -3.78049743e-01],
       [-1.58495890e+00, -2.29358092e-01],
       [-6.84014877e-01, -7.02363653e-01],
       [-3.38633141e-02, -3.40230691e+00],
       [-1.60686724e+00, -2.23787253e-01],
       [-2.

In [12]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
score = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
p_score = precision_score(y_test,y_pred)
r_score = recall_score(y_pred, y_test)
c_report = classification_report(y_test, y_pred)
print(score)
print(cm)
print(p_score)
print(r_score)
print(c_report)


0.8466666666666667
[[118  17]
 [ 29 136]]
0.8888888888888888
0.8888888888888888
              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



### Hyperparameter Tuning and Cross Validation

### GridSeachCV

In [13]:
model = LogisticRegression(max_iter=5000)
# penalty = ['l1', 'l2', 'elasticnet'] 
penalty = ['l2']
c_values = [100,10,1.0,0.1,0.01]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

| Penalty     | Supported Solvers                        |
|-------------|-------------------------------------------|
| `l1`        | `liblinear`, `saga`                      |
| `l2`        | `newton-cg`, `lbfgs`, `liblinear`, `sag`, `saga` |
| `elasticnet`| `saga`                                   |
| `none`      | `newton-cg`, `lbfgs`, `sag`, `saga`      |

In [14]:
params = dict(penalty=penalty,C=c_values,solver=solver)

In [15]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [16]:
# GridSearch CV
from sklearn.model_selection import GridSearchCV
Grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [17]:
Grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=5000), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [18]:
Grid.fit(x_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=5000), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01], 'penalty': ['l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [19]:
Grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}

In [20]:
y_pred_grid = Grid.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
score = accuracy_score(y_test,y_pred_grid)
cm = confusion_matrix(y_test,y_pred_grid)
p_score = precision_score(y_test,y_pred_grid)
r_score = recall_score(y_test,y_pred_grid)
c_report = classification_report(y_test, y_pred_grid)
print(score)
print(cm)
print(p_score)
print(r_score)
print(c_report)

0.8533333333333334
[[124  11]
 [ 33 132]]
0.9230769230769231
0.8
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



### Randomised SearchCV

In [22]:
from sklearn.model_selection import RandomizedSearchCV
model = LogisticRegression()
randomcv = RandomizedSearchCV(estimator=model,param_distributions=params,cv=5)

In [24]:
randomcv.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l2'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']})

In [25]:
randomcv.best_score_

np.float64(0.8771428571428572)

In [27]:
y_pred_random = randomcv.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
score = accuracy_score(y_test,y_pred_grid)
cm = confusion_matrix(y_test,y_pred_grid)
p_score = precision_score(y_test,y_pred_grid)
r_score = recall_score(y_test,y_pred_grid)
c_report = classification_report(y_test, y_pred_grid)
print(score)
print(cm)
print(p_score)
print(r_score)
print(c_report)

0.8533333333333334
[[124  11]
 [ 33 132]]
0.9230769230769231
0.8
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300

